# enable scrolling with mouse without having to explicitly change to scroll mode.
setw -g mouse on

# enable more scroll history, 10K will consume ~5MB memory per tmux pane.
setw -g history-limit 10000
